### ISSUE TITLE
Add ability to change schedule source file

### ISSUE THREAD

**Issue by BrianJKoopman** [simonsobs/scheduler-server#5]
Since early on we will be changing the master schedule text file to test different scan patterns, it'd be great if there was a way to do this without modification to the source code.

**Comment by guanyilun** [comment]
what's your preference? currently it's possible to overwrite any part of the configuration by passing in the right options as part of your request. See [this line](https://github.com/simonsobs/scheduler-server/blob/main/src/scheduler_server/app.py#L97) and [this line](https://github.com/simonsobs/scheduler-server/blob/main/src/scheduler_server/app.py#L77) for example. This corresponds to the `config` here which probably is default to empty (meaning no overwrite):
```
POST /api/v1/schedule/
{
"t0": "2022-01-01 12:00",
"t1": "2022-01-01 14:00",
"policy": {"policy": "dummy", "config": {}}
}
```
